image:
  name: pause-container
  sourceRepository: github.com/kubernetes/kubernetes/blob/master/build/pause/Dockerfile
  repository: k8s.gcr.io/pause
  tag: "3.7"
  pullPolicy: IfNotPresent

pools:
  etcd:
    nodeLabels:
      pool.worker.gardener.cloud/dedicated-for: etcd
    replicaCount: 1
    resources:
      requests:
        cpu: 300m
        memory: 1G
